name: Pulumi Infrastructure Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write   
  contents: read    

env:
  PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
  PULUMI_BACKEND_URL: ${{ secrets.PULUMI_BACKEND_URL }}
  AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  pulumi-infrastructure:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ASSUME_ROLE }}
          aws-region: us-east-1  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a requirements.txt

      - name: Pulumi Preview
        uses: pulumi/actions@v5
        with:
          command: preview
          stack-name: prod 
              

  pulumi-up:
    runs-on: ubuntu-latest
    needs: pulumi-infrastructure
    if: ${{ success() }}  
    environment: production 
    steps:
      - uses: actions/checkout@v4

      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v2

      - name: Pulumi Up
        uses: pulumi/actions@v5
        with:
          command: up
          stack-name: prod
          options: --yes

  pulumi-destroy:
    runs-on: ubuntu-latest
    environment: destroy 
    needs: pulumi-up 
    if: ${{ success() }}  
    steps:
      - uses: actions/checkout@v4

      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v2

      - name: Pulumi Destroy
        uses: pulumi/actions@v5
        with:
          command: destroy
          stack-name: prod
          options: --yes
